### ISSUE TITLE
implement stdin_process

### ISSUE THREAD

**Issue by flip40** [CS149-3/homework6#3]
This is the function called by the 5th child process. This should request user input, take one line, and pass this input to the pipe for printing, along with the timestamp of when the input was received.

This process should terminate after 30 seconds by exiting the function (don't end the process yourself).

Variables provided to the function:
process: integer for the process number (4)
pipe: the pipe that should be written to with write()
start_time: the start time in milliseconds of the parent process. Use this to determine how long the process has been running for your time stamp in messages (get_current_time() - start_time).

**Comment by seanvail** [comment]
Okay, stdin implemented, didn't see any conflicts so I just pushed it straight to master branch.

On note: I can't figure out a way to get the other processes to temporarily stop printing so that a message can be easily entered. But if you just keep typing through the chaos, the message will be received in the order you typed it up until you hit enter.

**Comment by flip40** [comment]
Just a comment on your note, I'll just remove the output other than started / stopped prints. The processes print to an output.txt anyways, so there really isn't need for the other prints other than for debug reasons.
